stages:
  - build
  - test
  - quality
  - package
  - deploy

cache:
  paths:
    - .m2/repository
  key: "$CI_JOB_NAME"

variables:
  PLAYWD: ip172-18-0-92-bj1fer0j98i000ca3pdg

build_job:
  stage: build
  script:
    - echo 'OK'
#    - ./mvnw compile
#      -Dhttps.protocols=TLSv1.2
#      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
#      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
#      -Dorg.slf4j.simpleLogger.showDateTime=true
#      -Djava.awt.headless=true
#      --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true
  image: openjdk:8-alpine

test_job:
  stage: test
  script:
    - echo 'OK'
#    - ./mvnw test
#      -Dhttps.protocols=TLSv1.2
#      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
#      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
#      -Dorg.slf4j.simpleLogger.showDateTime=true
#      -Djava.awt.headless=true
#      --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true
  image: openjdk:8-alpine

code_quality_job:
  stage: quality
  allow_failure: true
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - echo 'OK'
#    - mkdir codequality-results
#    - docker run
#        --env CODECLIMATE_CODE="$PWD"
#        --volume "$PWD":/code
#        --volume /var/run/docker.sock:/var/run/docker.sock
#        --volume /tmp/cc:/tmp/cc
#        codeclimate/codeclimate analyze -f html > ./codequality-results/index.html
  artifacts:
    paths:
      - codequality-results/

package_job:
  stage: package
  services:
    - docker:stable-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - echo 'OK'
#    - apk add --no-cache docker
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#    - ./mvnw install -PbuildDocker -DskipTests=true -DpushImage
#      -Dhttps.protocols=TLSv1.2
#      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
#      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
#      -Dorg.slf4j.simpleLogger.showDateTime=true
#      -Djava.awt.headless=true
#      --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true
  image: openjdk:8-alpine

deploy_staging_job:
  stage: deploy
  image: docker:stable
  script:
    - echo 'OK'
#    - apk add --no-cache openssh-client py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
#    - pip install docker-compose
#    - export DOCKER_HOST=tcp://$PLAYWD.direct.labs.play-with-docker.com:2375
#    - docker-compose down
#    - docker-compose up -d
  environment:
    name: staging
    url: http://$PLAYWD-8080.direct.labs.play-with-docker.com